# Generated by Django 4.2.4 on 2023-09-13 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_product_mst'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product_sub_category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Product_price', models.CharField(max_length=50)),
                ('Product_model', models.CharField(max_length=50)),
                ('Product_ram', models.CharField(max_length=50)),
                ('Product_img', models.ImageField(default='', upload_to='image/')),
            ],
        ),
    ]
