# Generated by Django 4.2.4 on 2023-09-13 13:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_product_sub_cat_delete_product_sub_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product_sub_cat',
            old_name='Product_img',
            new_name='product_img',
        ),
        migrations.RenameField(
            model_name='product_sub_cat',
            old_name='Product_model',
            new_name='product_model',
        ),
        migrations.RenameField(
            model_name='product_sub_cat',
            old_name='Product_price',
            new_name='product_price',
        ),
        migrations.RenameField(
            model_name='product_sub_cat',
            old_name='Product_ram',
            new_name='product_ram',
        ),
    ]
